import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const header = '// Generated by scripts/build.mjs. Do not edit.\n';

const runtime = `
function stateRank(state) {
  if (state === 'closed') {
    return 0;
  }
  if (state === 'open') {
    return 1;
  }
  return 2;
}

function freezePhone(phone) {
  Object.freeze(phone.resolution_px);
  Object.freeze(phone.also_known_as);
  return Object.freeze(phone);
}

const { phones: phoneList, ...rest } = dataset;
Object.freeze(rest.notes);
Object.freeze(rest.units);
const phones = Object.freeze(phoneList.map(freezePhone));
const meta = Object.freeze(rest);

function getPhone(id) {
  for (const phone of phones) {
    if (phone.id === id) {
      return phone;
    }
  }
  return undefined;
}

function findPhones(query) {
  const needle = query.toLowerCase();
  const matches = [];
  for (const phone of phones) {
    if (phone.name.toLowerCase().includes(needle) || phone.id.toLowerCase().includes(needle)) {
      matches.push(phone);
      continue;
    }
    for (const alias of phone.also_known_as) {
      if (alias.toLowerCase().includes(needle)) {
        matches.push(phone);
        break;
      }
    }
  }
  return matches;
}

function getProduct(productId) {
  const matches = [];
  for (const phone of phones) {
    if (phone.product_id === productId) {
      matches.push(phone);
    }
  }
  matches.sort((left, right) => stateRank(left.state) - stateRank(right.state));
  return matches;
}
`;

const jsonText = await readFile(join(root, 'data', 'iphones.json'), 'utf8');
const dataset = JSON.parse(jsonText);
const literal = JSON.stringify(dataset, null, 2);
const body = runtime.trim() + '\n';

const dataJs = header + 'export default ' + literal + ';\n';
const indexJs = header + "import dataset from './data.js';\n" + body + 'export { phones, meta, getPhone, findPhones, getProduct };\n';
const indexCjs = header + "'use strict';\nconst dataset = " + literal + ';\n' + body + 'module.exports = { phones, meta, getPhone, findPhones, getProduct };\n';

const dist = join(root, 'dist');
await mkdir(dist, { recursive: true });
await writeFile(join(dist, 'data.js'), dataJs);
await writeFile(join(dist, 'index.js'), indexJs);
await writeFile(join(dist, 'index.cjs'), indexCjs);
